#!/usr/bin/python3

from sys import argv

args = argv[1:]
for x in range(len(args)):
    num = int(args[x])
    for i in range(2, num):
        if num % i == 0:
            print(f"{num}={int(num/i)}*{i} ")
            break
